name: BTC Daily Report Push

on:
  schedule:
    - cron: '0 0 * * *'   # UTC 0点，对应北京时间早上8点
    - cron: '0 12 * * *'  # UTC 12点，对应北京时间晚上8点
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装Python依赖
        run: |
          pip install requests openai beautifulsoup4 lxml

      - name: Install dependencies
        run: |
          pip install openai==0.28 requests   # ← 这里加了版本号 ✅
          pip install yfinance openai requests beautifulsoup4

      - name: Run BTC Report Script
        run: python btc_report.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
          SERVER_CHAN_KEY: ${{ secrets.SERVER_CHAN_KEY }}


