name: BTC Daily Report Preview

on:
  schedule:
    - cron: '0 2 * * *'  # UTC 2点 = 北京时间10点
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate BTC Report Only (No Push)
        run: |
          echo "调用 GPT 生成快报..."
          response=$(curl -s https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer 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" \
          -d '{
            "model": "gpt-4",
            "messages": [{"role": "user", "content": "生成一份今天的BTC快报，包含DXY，AHR999，ETF资金流趋势，总结流动性状况和操作建议，语气专业简洁，用中文回答。"}],
            "temperature": 0.7
          }')

          echo "GPT原始响应："
          echo "$response"

          content=$(echo "$response" | grep -oP '"content":\s*"\K([^"]+)' | sed 's/\\n/\n/g')

          echo "生成的快报内容："
          echo "$content"
